prefix = "/app/backend/"
stop-words = "/app/backend/stopwords.txt"

dataset = "cranfield"
corpus = "line.toml"
index = "idx"

query-judgements = "/app/backend/cranfield-qrels.txt"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"

[query-runner]
query-path = "/app/backend/cranfield-queries.txt"
query-id-start = 1
