prefix = "."

dataset = "experts"
corpus = "line.toml"
index = "idx"

stop-words = "experts/stopwords.txt"

query-judgements = "experts/experts-qrels.txt"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"

[query-runner]
query-path = "experts/experts-queries.txt"
query-id-start = 0
